[global]
developmentMode = false
showWarningOnDirectExecution = false

[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 10
maxMessageSize = 10
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "sans serif"

[runner]
magicEnabled = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
